application: sabandija
version: 1
runtime: python
api_version: 1


handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /load
  script: sabandija_loader.py

- url: /.*
  script: sabandija.py

  
  

